blueprint:
  name: Quiet Mode Executor
  description: >
    Исполнитель тихого режима: применяет настройки громкости, отключает домофон,
    управляет светом, отправляет уведомления и т.д.
  domain: automation

  input:

    # --- УСТРОЙСТВА ДЛЯ ИЗМЕНЕНИЯ ГРОМКОСТИ ---
    media_players:
      name: Медиаплееры
      description: "Колонки, ТВ или другие аудиоустройства"
      selector:
        entity:
          domain: media_player
          multiple: true

    # --- ГРОМКОСТЬ ДЛЯ ТИХОГО РЕЖИМА ---
    volume_level:
      name: Громкость (0–1)
      description: "Громкость, которую установить в тихом режиме"
      selector:
        number:
          min: 0.01
          max: 1
          step: 0.01
      default: 0.1

    # --- ВКЛЮЧАТЬ ЛИ ТИХИЙ СВЕТ ---
    quiet_lights:
      name: Тихие светильники
      description: "Свет, который включается в ночном режиме"
      selector:
        entity:
          domain: light
          multiple: true

    quiet_brightness:
      name: Яркость тихого света
      selector:
        number:
          min: 1
          max: 255
          step: 1
      default: 10

    # --- ДОМФОН ---  
    disable_doorbell:
      name: Отключать входящий звонок домофона?
      selector:
        boolean: {}
      default: true

    doorbell_sensor:
      name: Сенсор домофона
      description: "Сенсор, фиксирующий входящий звонок"
      selector:
        entity: {}

    # --- УВЕДОМЛЕНИЯ ---  
    telegram_chat_id:
      name: Telegram Chat ID
      selector:
        text: {}

    android_device:
      name: Android устройство
      description: "Push-уведомление"
      selector:
        entity:
          integration: mobile_app

    notify_text:
      name: Текст уведомления
      selector:
        text: {}
      default: "Тихий режим активирован"

# ============================================================
#                           ТРИГГЕР
# ============================================================
trigger:
  - platform: event
    event_type: quiet_mode_executor_run
    id: run

# ============================================================
#                           ПЕРЕМЕННЫЕ
# ============================================================
variables:
  media_players: !input media_players
  volume_level: !input volume_level
  quiet_lights: !input quiet_lights
  quiet_brightness: !input quiet_brightness
  disable_doorbell: !input disable_doorbell
  doorbell_sensor: !input doorbell_sensor
  android_device: !input android_device
  telegram_chat_id: !input telegram_chat_id
  notify_text: !input notify_text

# ============================================================
#                           ДЕЙСТВИЯ
# ============================================================
action:

  # Устанавливаем громкость
  - service: media_player.volume_set
    target:
      entity_id: "{{ media_players }}"
    data:
      volume_level: "{{ volume_level }}"

  # Включаем тихий свет
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ quiet_lights | count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ quiet_lights }}"
            data:
              brightness: "{{ quiet_brightness }}"

  # Отключаем домофон (если требуется)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ disable_doorbell }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ doorbell_sensor }}"

  # Telegram уведомление
  - service: telegram_bot.send_message
    data:
      chat_id: "{{ telegram_chat_id }}"
      message: "{{ notify_text }}"

  # Push уведомление Android
  - service: notify.mobile_app_{{ android_device.split('.')[1] }}
    data:
      title: "Тихий режим"
      message: "{{ notify_text }}"
