blueprint:
  name: Quiet Mode Trigger
  description: >
    Управление интеллектуальным "Тихим режимом". Включение по времени или вручную,
    отправка уведомлений в Android и Telegram, управление громкостью устройств,
    запуск Quiet Mode Executor для применения настроек.
  domain: automation

  input:

    # --- ВРЕМЯ ЗАПУСКА ТИХОГО РЕЖИМА ---
    start_time:
      name: Время начала
      description: "Когда автоматически включать тихий режим"
      selector:
        time: {}

    # --- ВРЕМЯ ЗАВЕРШЕНИЯ ТИХОГО РЕЖИМА ---
    end_time:
      name: Время окончания
      description: "Когда автоматически отключать тихий режим"
      selector:
        time: {}
      default: "07:00"

    # --- РУЧНОЙ ЗАПУСК (сенсор / кнопка / событие) ---
    manual_trigger:
      name: Ручной запуск
      description: "Событие или сенсор, который включает тихий режим вручную"
      selector:
        entity: {}

    # --- УСТРОЙСТВА ДЛЯ ТИХОГО РЕЖИМА ---
    quiet_devices:
      name: Устройства
      description: "Устройства, на которые влияет тихий режим (динамики, ТВ)"
      selector:
        entity:
          multiple: true

    # --- ГРОМКОСТЬ В ПРОЦЕНТАХ ---
    volume_percent:
      name: Громкость (%) 
      description: "Громкость в процентах, если выбран режим проценты"
      selector:
        number:
          min: 1
          max: 100
          step: 1
      default: 10

    # --- ГРОМКОСТЬ В ФОРМАТЕ 0–1 ---
    volume_level:
      name: Громкость (0–1)
      description: "Громкость медиаплееров, если выбран формат 0–1"
      selector:
        number:
          min: 0.01
          max: 1
          step: 0.01
      default: 0.1

    # --- ЧТО ИСПОЛЬЗОВАТЬ: % или 0–1 ---
    use_percent:
      name: Использовать проценты?
      description: "true = volume_percent, false = volume_level"
      selector:
        boolean: {}
      default: true

    # --- УСТРОЙСТВО ANDROID ---
    android_device:
      name: Android устройство
      description: "Куда отправлять push уведомления"
      selector:
        entity:
          integration: mobile_app

    # --- ЧАТ TELEGRAM ---
    telegram_chat_id:
      name: Telegram Chat ID
      description: "ID чата Telegram"
      selector:
        text: {}

    # --- ТЕКСТ УВЕДОМЛЕНИЙ ПОЛЬЗОВАТЕЛЯ ---
    notify_custom_text:
      name: Пользовательский текст уведомления
      description: "Если пусто — используется текст по умолчанию"
      selector:
        text: {}
      default: ""

# ===========================================================
#                     ТРИГГЕРЫ
# ===========================================================
trigger:

  # Автоматическое включение по времени
  - platform: time
    at: !input start_time
    id: auto_start

  # Автоматическое выключение по времени
  - platform: time
    at: !input end_time
    id: auto_end

  # Ручной запуск
  - platform: state
    entity_id: !input manual_trigger
    to: "on"
    id: manual_start

# ===========================================================
#                     ПЕРЕМЕННЫЕ
# ===========================================================
variables:
  quiet_devices: !input quiet_devices
  android_device: !input android_device
  telegram_chat_id: !input telegram_chat_id
  use_percent: !input use_percent
  notify_custom_text: !input notify_custom_text
  vol_percent: !input volume_percent
  vol_level: !input volume_level

# ===========================================================
#                     ДЕЙСТВИЯ
# ===========================================================
action:

  - choose:

      # -----------------------------
      #  ВКЛЮЧЕНИЕ ТИХОГО РЕЖИМА
      # -----------------------------
      - conditions:
          - condition: trigger
            id:
              - auto_start
              - manual_start
        sequence:

          # Устанавливаем громкость
          - choose:
              # формат проценты
              - conditions:
                  - condition: template
                    value_template: "{{ use_percent }}"
                sequence:
                  - service: media_player.volume_set
                    target:
                      entity_id: "{{ quiet_devices }}"
                    data:
                      volume_level: "{{ vol_percent / 100 }}"

              # формат 0–1
              - conditions:
                  - condition: template
                    value_template: "{{ not use_percent }}"
                sequence:
                  - service: media_player.volume_set
                    target:
                      entity_id: "{{ quiet_devices }}"
                    data:
                      volume_level: "{{ vol_level }}"

          # Телеграм уведомление
          - service: telegram_bot.send_message
            data:
              chat_id: "{{ telegram_chat_id }}"
              message: >-
                {{ notify_custom_text if notify_custom_text != "" else
                "Тихий режим включён" }}

          # Android push
          - service: notify.mobile_app_{{ android_device.split('.')[1] }}
            data:
              title: "Тихий режим"
              message: >-
                {{ notify_custom_text if notify_custom_text != "" else
                "Тихий режим включён" }}
              data:
                channel: alarm_stream
                actions:
                  - action: "delay_30"
                    title: "Отложить на 30 минут"
                  - action: "delay_60"
                    title: "Отложить на 1 час"
                  - action: "delay_120"
                    title: "Отложить на 2 часа"

          # Запуск Executor
          - service: script.quiet_mode_executor

      # -----------------------------
      #  ВЫКЛЮЧЕНИЕ ТИХОГО РЕЖИМА
      # -----------------------------
      - conditions:
          - condition: trigger
            id:
              - auto_end
        sequence:

          - service: media_player.volume_set
            target:
              entity_id: "{{ quiet_devices }}"
            data:
              volume_level: 0.5

          - service: telegram_bot.send_message
            data:
              chat_id: "{{ telegram_chat_id }}"
              message: "Тихий режим завершён"

          - service: notify.mobile_app_{{ android_device.split('.')[1] }}
            data:
              title: "Тихий режим"
              message: "Тихий режим завершён"
